---
# tasks file for win_rm_kerb_role
- name: Install kerberos packages
  yum:
    name: '{{ item }}'
    state: latest
  with_items: "{{ redhat_pkg }}"

- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ redhat_pip }}"

- name: Copy the client configuration file
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
