---
# tasks file for kerberos
#
# -----------------------------------------------------------------------------
# Setup Kerberos
# -----------------------------------------------------------------------------
#

- include_tasks: kerb.yml
  tags:
    - kerberos
