---
- name: Copy cert into place
  become: true
  copy:
    src: "{{ tower_ssl_cert }}"
    dest: /etc/tower/tower.cert
  notify:
    - Restart Ansible tower service

- name: Copy cert key into place
  become: true
  copy:
    src: "{{ tower_ssl_key }}"
    dest: /etc/tower/tower.key
  notify:
    - Restart Ansible tower service
...
