---
namespace: infra
name: aap_utilities
version: 2.2.2
description: A collection of utility roles for usage with Ansible Automation Platform
readme: README.md
authors:
    - Sean Sullivan @sean-m-sullivan
    - Tom Page @Tompage1994
    - David Danielsson @djdanielsson
repository: https://github.com/redhat-cop/aap_utilities
issues: https://github.com/redhat-cop/aap_utilities/issues
build_ignore:
    - galaxy.yml.j2
    - .github
    - .markdownlint.yml
    - .ansible-lint
    - .yamllint.yml
    - .pre-commit-config.yaml
    - .gitignore
    - .gitattributes
license:
    - GPL-3.0-or-later
tags:
    - ansible_automation_platform
    - aap
    - aap_utils
    - aap_utilities
    - collection
    - utilities
    - utils
    - tower
    - tower_utilities
    - tower_utils
    - infrastructure
dependencies:
    "ansible.posix": ">=1.0.0"
    "kubernetes.core": ">=2.2.0"
...
