---
# defaults file for ansible-tower-manage

############################################################
#               Tower Installation Vars                    #
############################################################

# Working location for installation files
tower_working_location: "/var/tmp"

# Tower variables
tower_admin_user: "admin"
tower_admin_password: "password"

# Tower secret key
tower_secret_key: "mysecret"

# Postgresql variables

# pg_hostname: pg.tower.example.com
tower_pg_database: "awx"
tower_pg_username: "awx"
tower_pg_password: "password"
pg_port: 5432
pg_sslmode: "prefer" # set to 'verify-full' for client-side enforced SSL

tower_releases_url: https://releases.ansible.com/ansible-tower/setup_openshift/
tower_setup_file: ansible-tower-openshift-setup-{{ tower_release_version }}.tar.gz

############################################################
#               Openshift vars.                 #
############################################################

# Note: The user running this installer will need cluster-admin privileges.
# Tower's job execution container requires running in privileged mode,
# and a service account must be created for auto peer-discovery to work.

openshift_host: https://openshift.example.com
openshift_skip_tls_verify: true
openshift_project: tower
openshift_user: kubeadmin

# persistant volume claim size
pvc_claim_size: 10gi
