---
galaxy_info:
  role_name: redhat_cop.tower_utilities.tower_certs
  author: Tom Page
  description: Role to install Ansible Tower Certificates
  company: Red Hat

  license: license (MIT)

  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - linux
    - system
    - ansible
    - cert
    - certs

dependencies: []
...
