---
# vars file for install_ocp
tower_releases_url: https://releases.ansible.com/ansible-tower/setup_openshift/
tower_setup_file: ansible-tower-openshift-setup-{{ tower_release_version }}.tar.gz

# Use the default tower installation template
pre_tasks_process_template: False