---
############################################################
#               Ansible Tower backup settings.                 #
############################################################

# Default backup vars, these are default from installer
backup_dest: "{{ playbook_dir }}/"