---
galaxy_info:
  role_name: redhat_cop.tower_utilities.kerberos
  author: Sean Sullivan
  description: Role to setup Kerberos
  company: Red Hat

  license: license (MIT)

  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - linux
    - system
    - ansible
    - kerberos
